# Site settings
title: Dirty Unicorns
email: ''
description: "A feature packed custom ROM for over 20 different Android devices"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dirtyunicorns.com" # the base hostname & protocol for your site
twitter_username: _dirtyunicorns_
github_username:  DirtyUnicorns
google_plus_com: '109738128866939227235'  # Community link

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: true
disqus_shortname: 'dirtyunicorns'

# Build settings
markdown: kramdown

permalink: "/:title"

more_vert:		
  option1:		
    name: Cool Option 1		
    link: www.myawesomelink.com		
  option2:		
    name: Cool Option 2		
    link: www.myawesomelink.com		
  option3:		
    name: Cool Option 3		
    link: www.myawesomelink.com